In [1]:
import pandas as pd

In [2]:
asdf = pd.read_csv("./PAYMENT_SHEET.csv")

In [3]:
asdf

,Code,Name,Designation,Site/Branches,DATE OF JOINING,1,2,3,4,5,...,Leave,Month,Salary,Rate,Month's Salary,Current Adv (Tally),Adjustment,PF/ESIC,Final Payable,Any Short Remarks
0,JKEPL001,Deepak Kumar Tripathi,Mech. Engineer,Bagha,NaN,NaN,NaN,NaN,NaN,NaN,...,14.0,31.0,25000.0,806.0,13710,NaN,NaN,NaN,13710,NaN
1,JKEPL002,Arbind kumar singh,Lab Tech,RACK POINT,NaN,P,P,P,P,P,...,0.0,31.0,18000.0,581.0,18000,5400.0,1000.0,1192.0,15808,NaN
2,JKEPL004,Praduman Giri,Supervisor,EKMA-MASRAKH,NaN,P,P,P,P,P,...,0.0,31.0,16500.0,532.0,16500,NaN,NaN,1035.0,15465,OK
3,JKEPL005,Ranjeet Kumar singh,Supervisor,Malmaliya,NaN,P,P,P,P,P,...,2.0,31.0,13000.0,419.0,12161,NaN,NaN,896.0,11265,NaN
4,JKEPL006,Pradhan,Guard,DAUDPUR PLANT,NaN,P,P,P,P,P,...,0.0,31.0,8000.0,258.0,8000,-68159.0,NaN,113.0,76046,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,JKEPL240,Bhavishaya Kumar,Guard,Indra-Doharighat,15-12-2021,NaN,NaN,NaN,NaN,NaN,...,26.0,31.0,0.0,0.0,0,NaN,NaN,NaN,0,HOLD BY MR.NKS
110,JKEPL241,Pankaj kumar,Fiori Helpher,Indra-Doharighat,15-12-2021,NaN,NaN,NaN,NaN,NaN,...,21.0,31.0,3000.0,97.0,968,500.0,NaN,NaN,468,NaN
111,JKEPL242,Vikki kumar singh,Surveyer Helpher,RACK POINT,15-12-2021,NaN,NaN,NaN,NaN,NaN,...,14.0,31.0,7000.0,226.0,3839,200.0,NaN,NaN,3639,NaN
112,JKEPL243,Rajesh Giri,Cook,EKMA-MASRAKH,19-12-2021,NaN,NaN,NaN,NaN,NaN,...,18.0,31.0,NaN,NaN,0,500.0,NaN,NaN,-500,NOT CONFIRMED BY MR.NKS
113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1337832,385207.0,62797.0,13333.0,1291847,NaN

In [4]:
asdf['Salary'].max()

55000.0

In [5]:
asdf['Salary'].mean()

14259.545454545454

In [6]:
asdf['Salary'][asdf['DATE OF JOINING']=='Rain']

Series([], Name: Salary, dtype: float64)

In [ ]:
print("Hello world")